
services:
  db:
    container_name: forum_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=devkiki
      - POSTGRES_PASSWORD=devkiki77
      - POSTGRES_DB=forum
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db